apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: TXlTZWN1cmVQYXNzMTIz
  MYSQL_DATABASE: c3R1ZGVudF9tYW5hZ2VtZW50X2Ri
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: TXlTZWN1cmVQYXNzMTIz

